# ==================================================================
# RELEASE MANAGER GITHUB ACTION
# ==================================================================
name: release-manager

description: Complete version & release management including changelog creation, version bumps and GitHub release.

inputs:

    repository:
        description: Name of repository to release (include owner's name - eg. ragdata/release-manager)
        required: false
        default: ${{ github.repository }}

    username:
        description: Username of the user responsible for the release
        required: false
        default: ${{ github.actor }}

    commit-message:
        description: Commit message used when bumped files are committed
        required: false
        default: 'chore(release): version bumped to {{version}}'

    token:
        description: Personal Access Token used to authenticate access
        required: false
        default: ${{ secrets.GITHUB_TOKEN }}

    release-type:
        description: The type of release to perform
        required: false
        default: 'patch'

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - --repository ${{ inputs.repository }}
        - --user ${{ inputs.username }}
        - --commit-message ${{ inputs.commit-message }}
        - --token ${{ inputs.token }}
        - --release-type ${{ inputs.release-type }}
branding:
    icon: 'shield'
    color: 'red'
